### PR TITLE
Improve retrieving ip of container

### PR DESCRIPTION
**Pull request by Yannik**

### CODE REVIEW

**Comment by chrismeyersfsu** [comment]
@Yannik Tests failing. I recall this being tricky, hence the `.sh` execution.

**Comment by Yannik** [comment]
I'll have another look at this.

**Comment by Yannik** [comment]
afaik, the next test run should not produce any errors.

**Comment by Yannik** [comment]
@chrismeyersfsu Any update on this?

**Comment by Yannik** [comment]
Hey @chrismeyersfsu, is there anything wrong with this PR that prevents you from merging?

**Pull request merged**
